@startuml

abstract class Entity {
  - id: uuid.UUID
  - name: str
  - label: str
  - description: str
  - position: tuple[int, int]
  + get_id() -> uuid.UUID
  + set_name(str) -> None
  + get_name() -> str
  + set_label(label: str) -> None
  + get_label() -> str
  + set_description(str) -> None
  + get_description() -> str
  + set_position(position: tuple[int, int]) -> None
  + get_position() -> tuple[int, int]
}

Tile "1" *-- "many" Entity : contains >

@enduml