@startuml

enum Direction {
  N
  NE
  E
  SE
  S
  SW
  W
  NW
}

class Vector2 {
  -x: int
  -y: int
  +set_x(x: int): void
  +get_x(): int
  +set_y(y: int): void
  +get_y(): int
  +set_position(position: Vector2): void
  +get_position(): Vector2
  +add(other: Vector2): Vector2
  +subtract(other: Vector2): Vector2
  +equals(other: Vector2): bool
  +manhattan_distance(other: Vector2): int
  +direction_to(other: Vector2): Direction
  +adjacent_positions(): List[Vector2]
}

Direction -- Vector2 : < "direction to"

@enduml