"""Added old tile data for offline -> online players

Revision ID: 097dfc40e250
Revises: 2ec10cc2bbea
Create Date: 2025-07-26 18:35:05.737927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097dfc40e250'
down_revision: Union[str, Sequence[str], None] = '2ec10cc2bbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('relog_tile_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'relog_tile_id')
    # ### end Alembic commands ###
