"""Added polymorphic identities

Revision ID: 8aa322b703e3
Revises: 9205bab516be
Create Date: 2025-07-16 16:23:40.194746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa322b703e3'
down_revision: Union[str, Sequence[str], None] = '9205bab516be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entities_tile_id_fkey'), 'entities', type_='foreignkey')
    op.create_foreign_key(None, 'entities', 'tiles', ['tile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.create_foreign_key(op.f('entities_tile_id_fkey'), 'entities', 'tiles', ['tile_id'], ['id'])
    # ### end Alembic commands ###
