"""Fixed naming mismatch. Added polymorphism

Revision ID: 9205bab516be
Revises: b8b0a003507d
Create Date: 2025-07-15 21:41:42.239885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9205bab516be'
down_revision: Union[str, Sequence[str], None] = 'b8b0a003507d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_gain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grass_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('consumable')
    op.drop_table('grass_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grass_field',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], name=op.f('grass_field_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('grass_field_pkey'))
    )
    op.create_table('consumable',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_gain', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['items.id'], name=op.f('consumable_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consumable_pkey'))
    )
    op.drop_table('grass_fields')
    op.drop_table('consumables')
    # ### end Alembic commands ###
