"""Updated models (levels: +attr(z_index); entity: +attr(type), -attr(name); human: +attr(name)

Revision ID: b8b0a003507d
Revises: cbda28be7411
Create Date: 2025-07-15 20:40:06.903412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b0a003507d'
down_revision: Union[str, Sequence[str], None] = 'cbda28be7411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('entities', 'name')
    op.add_column('humans', sa.Column('name', sa.String(), nullable=True))
    op.add_column('levels', sa.Column('z_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'z_index')
    op.drop_column('humans', 'name')
    op.add_column('entities', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('entities', 'type')
    # ### end Alembic commands ###
