"""Initial clean schema

Revision ID: c5135bd8b082
Revises: 
Create Date: 2025-07-18 11:03:05.857132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5135bd8b082'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameboard',
    sa.Column('num_levels', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('username', 'id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('levels',
    sa.Column('gameboard_id', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['gameboard_id'], ['gameboard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('z_index', name='unique_level_heights')
    )
    op.create_table('tiles',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('is_wall', sa.Boolean(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('x_coord >= 0', name='check_x_nonneg'),
    sa.CheckConstraint('y_coord >= 0', name='check_y_nonneg'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'x_coord', 'y_coord', name='unique_coordinates')
    )
    op.create_index('tile_order', 'tiles', ['level_id', 'y_coord', 'x_coord'], unique=False)
    op.create_table('entities',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('perception_range', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_gain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spread_factor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['props.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggressive_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grass_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passive_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.CheckConstraint('id > 0', name='check_id_positive'),
    sa.ForeignKeyConstraint(['id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('passive_animals')
    op.drop_table('grass_fields')
    op.drop_table('aggressive_animals')
    op.drop_table('humans')
    op.drop_table('fields')
    op.drop_table('consumables')
    op.drop_table('animals')
    op.drop_table('props')
    op.drop_table('items')
    op.drop_table('actors')
    op.drop_table('entities')
    op.drop_index('tile_order', table_name='tiles')
    op.drop_table('tiles')
    op.drop_table('levels')
    op.drop_table('users')
    op.drop_table('gameboard')
    # ### end Alembic commands ###
