"""Added user relation. Shifted attributes of actor and actor subclass

Revision ID: f80129f71409
Revises: 8aa322b703e3
Create Date: 2025-07-17 22:27:59.357811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80129f71409'
down_revision: Union[str, Sequence[str], None] = '8aa322b703e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.CheckConstraint('id > 0', name='check_id_positive'),
    sa.ForeignKeyConstraint(['id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='unique_username')
    )
    op.add_column('actors', sa.Column('hunger', sa.Integer(), nullable=False))
    op.add_column('actors', sa.Column('strength', sa.Integer(), nullable=False))
    op.drop_column('aggressive_animals', 'strength')
    op.drop_column('animals', 'hunger')
    op.drop_column('humans', 'hunger')
    op.drop_column('humans', 'name')
    op.drop_column('humans', 'strength')
    op.create_unique_constraint('unique_level_heights', 'levels', ['z_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_level_heights', 'levels', type_='unique')
    op.add_column('humans', sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('humans', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('humans', sa.Column('hunger', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('animals', sa.Column('hunger', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('aggressive_animals', sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('actors', 'strength')
    op.drop_column('actors', 'hunger')
    op.drop_table('users')
    # ### end Alembic commands ###
