@startuml

abstract class Actor {
  -health: int
  -speed: float
  -task_list: List[Task]
  +get_health(): int
  +set_health(health: int): void
  +get_speed(): float
  +set_speed(speed: float): void
  +move(direction: Direction): void
  +add_task(task: Task): void
  +remove_task(task: Task): void
  +get_tasks(): List[Task]
  +sort_tasks(): void
  +perform_task(task: Task): void
}

Entity <|-- Actor

@enduml